[Definition]
failregex = ^<HOST> .* "(GET|POST|HEAD).*" \d+ .* "(SemrushBot|AhrefsBot|GPTBot|OpenAI|TikTokSpider|Bytespider|SERankingBacklinksBot|MJ12bot|DotBot|BLEXBot|PetalBot|YandexBot).*"$
ignoreregex =
